const CART_KEY='amora_fut_cart_v1',WA_CART='5585998022643';
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function getCart(){try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{return[]}}
function saveCart(c){localStorage.setItem(CART_KEY,JSON.stringify(c));renderCart()}
function cartCount(){return getCart().reduce((n,i)=>n+Number(i.qty||0),0)}
function addToCart(p,size,qty=1){const c=getCart(),key=p.id+'::'+(size||'ÚNICO'),max=p.stock&&size?Number(p.stock[size]||0):null,found=c.find(i=>i.key===key);if(found)found.qty=max?Math.min(max,found.qty+qty):found.qty+qty;else c.push({key,id:p.id,name:p.name,team:p.team||'',version:p.version||'',price:Number(p.price||0),size:size||'',qty:Number(qty||1),image:(p.images&&p.images[0])||p.image||'',stock:max});saveCart(c);openCart()}
function changeCart(key,d){const c=getCart(),i=c.findIndex(x=>x.key===key);if(i<0)return;const max=c[i].stock;c[i].qty=max?Math.min(max,c[i].qty+d):c[i].qty+d;if(c[i].qty<=0)c.splice(i,1);saveCart(c)}
function removeCart(key){saveCart(getCart().filter(x=>x.key!==key))}
function cartTotal(){return getCart().reduce((s,i)=>s+i.price*i.qty,0)}
function checkoutCart(){const c=getCart();if(!c.length)return;let t='Olá! Quero fazer um pedido na Amora Fut:\n\n';c.forEach((i,n)=>t+=(n+1)+'. '+i.name+(i.size?' — tamanho '+i.size:'')+' — '+i.qty+' un. — '+money(i.price*i.qty)+'\n');t+='\nTotal: '+money(cartTotal())+'\n\nGostaria de confirmar disponibilidade e pagamento.';window.open('https://wa.me/'+WA_CART+'?text='+encodeURIComponent(t),'_blank')}
function cartHTML(){return '<div id="cartOverlay" class="cart-overlay" onclick="if(event.target===this)closeCart()"></div><aside id="cartDrawer" class="cart-drawer"><div class="cart-head"><div><small>AMORA FUT</small><h2>Seu carrinho</h2></div><button class="cart-close" onclick="closeCart()">×</button></div><div id="cartItems" class="cart-items"></div><div class="cart-foot"><div class="cart-total"><span>Total</span><strong id="cartTotal">R$ 0,00</strong></div><button class="cart-checkout" onclick="checkoutCart()">Finalizar pelo WhatsApp</button><button class="cart-continue" onclick="closeCart()">Continuar comprando</button></div></aside><button id="cartFloat" class="cart-float" onclick="openCart()" aria-label="Abrir carrinho"><span>🛒</span><b id="cartBadge">0</b></button>'}
function renderCart(){const box=document.getElementById('cartItems'),badge=document.getElementById('cartBadge'),total=document.getElementById('cartTotal');if(!box)return;const c=getCart();if(badge)badge.textContent=cartCount();box.innerHTML=c.length?c.map(i=>'<div class="cart-item"><div class="cart-item-img">'+(i.image?'<img src="'+i.image+'" alt="">':'⚽')+'</div><div class="cart-item-main"><strong>'+i.name+'</strong><small>'+[i.team,i.size?'Tam. '+i.size:'',i.version].filter(Boolean).join(' • ')+'</small><div class="cart-item-bottom"><div class="qty"><button onclick="changeCart(\''+i.key+'\',-1)">−</button><b>'+i.qty+'</b><button onclick="changeCart(\''+i.key+'\',1)">+</button></div><strong>'+money(i.price*i.qty)+'</strong></div><button class="cart-remove" onclick="removeCart(\''+i.key+'\')">Remover</button></div></div>').join(''):'<div class="cart-empty"><div>🛒</div><strong>Seu carrinho está vazio</strong><span>Adicione suas camisas favoritas.</span></div>';if(total)total.textContent=money(cartTotal())}
function openCart(){document.body.classList.add('cart-open');renderCart()}function closeCart(){document.body.classList.remove('cart-open')}function initCart(){const r=document.getElementById('cartRoot');if(r)r.innerHTML=cartHTML();renderCart()}document.addEventListener('DOMContentLoaded',initCart);