const WA='5585998022643';
const fmt=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const pix=v=>v*.95;
const logo='/assets/images/logo.png';
let state={cat:'Todos',q:'',sort:'relevantes'};
const $=s=>document.querySelector(s);
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function initials(name){return name.split(/\s+/).slice(0,3).map(x=>x[0]).join('').toUpperCase();}
function card(p){const img=p.image?`<img src="${p.image}" alt="${esc(p.name)}" loading="lazy">`:'';return `<article class="card ${p.soldOut?'sold':''}" data-name="${esc(p.name.toLowerCase())}" data-cat="${p.category}"><button class="card-open" onclick="openProduct('${p.id}')" aria-label="Ver ${esc(p.name)}"><div class="photo">${img}<div class="placeholder"><span>${initials(p.name)}</span><small>AMORA FUT</small></div>${p.badge?`<b class="badge">${esc(p.badge)}</b>`:''}</div><div class="info"><div class="catline">${esc(p.category)} · ${esc(p.version)}</div><h3>${esc(p.name)}</h3><div class="price">${p.oldPrice?`<del>${fmt(p.oldPrice)}</del>`:''}<strong>${fmt(p.price)}</strong></div><div class="pix">ou ${fmt(pix(p.price))} no Pix</div><span class="cta">Ver detalhes</span></div></button></article>`}
function render(){let arr=PRODUCTS.filter(p=>(state.cat==='Todos'||p.category===state.cat)&&p.name.toLowerCase().includes(state.q));if(state.sort==='menor')arr.sort((a,b)=>a.price-b.price);if(state.sort==='maior')arr.sort((a,b)=>b.price-a.price);$('#grid').innerHTML=arr.map(card).join('')||`<div class="empty">Nenhuma camisa encontrada.</div>`;$('#count').textContent=`${arr.length} ${arr.length===1?'produto':'produtos'}`;}
function openProduct(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;$('#modal').innerHTML=`<div class="modal-bg" onclick="closeProduct(event)"><div class="modal" onclick="event.stopPropagation()"><button class="close" onclick="closeProduct()">×</button><div class="modal-photo">${p.image?`<img src="${p.image}" alt="${esc(p.name)}">`:`<div class="modal-placeholder"><span>${initials(p.name)}</span><small>AMORA FUT · CATÁLOGO VIP</small></div>`}</div><div class="modal-info"><div class="eyebrow">${esc(p.category)} · ${esc(p.version)}</div><h2>${esc(p.name)}</h2><div class="modal-price">${p.oldPrice?`<del>${fmt(p.oldPrice)}</del>`:''}<strong>${fmt(p.price)}</strong></div><div class="pix">5% de desconto no Pix · ${fmt(pix(p.price))}</div><p>Consulte tamanhos e disponibilidade pelo WhatsApp. Enviamos para todo o Brasil.</p><div class="actions"><a class="btn primary ${p.soldOut?'disabled':''}" ${p.soldOut?'aria-disabled="true"':'href="'+waLink(p)+'" target="_blank"'}>${p.soldOut?'Produto esgotado':'Pedir pelo WhatsApp'}</a></div></div></div></div>`;$('#modal').classList.add('show');document.body.classList.add('lock')}
function closeProduct(e){if(e&&e.target!==e.currentTarget)return;$('#modal').classList.remove('show');document.body.classList.remove('lock')}
function waLink(p){return 'https://wa.me/'+WA+'?text='+encodeURIComponent(`Olá! Vi no catálogo VIP da Amora Fut e tenho interesse na ${p.name} (${p.version}), por ${fmt(p.price)}. Gostaria de consultar os tamanhos disponíveis.`)}
function init(){document.querySelectorAll('.filter,.category-card').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter,.category-card').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.cat=b.dataset.cat;render()});const syncSearch=e=>{state.q=e.target.value.toLowerCase().trim();const other=e.target.id==='search'?$('#searchMobile'):$('#search');if(other)other.value=e.target.value;render()};if($('#search'))$('#search').oninput=syncSearch;if($('#searchMobile'))$('#searchMobile').oninput=syncSearch;$('#sort').onchange=e=>{state.sort=e.target.value;render()};render();}
window.openProduct=openProduct;window.closeProduct=closeProduct;document.addEventListener('DOMContentLoaded',init);
