const fmt=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const pix=v=>Number(v)*.95;
let state={cat:'Todos',q:'',sort:'relevantes'};
const $=s=>document.querySelector(s);
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function initials(name){return String(name).split(/\s+/).slice(0,3).map(x=>x[0]||'').join('').toUpperCase();}
function isCat(p,cat){if(cat==='Todos')return true;if(cat==='Lançamentos')return p.badge==='LANÇAMENTO';if(cat==='Ofertas')return !!p.oldPrice||p.badge==='OFERTA';return p.category===cat;}
function imageSrc(p){return p.image || (Array.isArray(p.images)&&p.images[0]) || ''}
function visual(p){const src=imageSrc(p);return src?`<img src="${esc(src)}" alt="${esc(p.name)}" loading="lazy" onerror="this.closest('.photo').classList.add('img-error')">`:''}
function card(p){const badge=p.badge?`<b class="badge ${p.soldOut?'sold-badge':''}">${esc(p.badge)}</b>`:'';return `<article class="card ${p.soldOut?'sold':''}"><a class="card-open" href="https://amorafut.github.io/amorafuta-cat-logo-vip/produto/${esc(p.id)}.html" target="_self" aria-label="Ver ${esc(p.name)}"><div class="photo">${visual(p)}<div class="placeholder" ${imageSrc(p)?'hidden':''}><div class="shirt-mark">${initials(p.name)}</div><span>AMORA FUT</span><small>STREETWEAR</small></div>${badge}<div class="quick">VER DETALHES</div></div><div class="info"><div class="catline">${esc(p.category)} <i>•</i> ${esc(p.version)}</div><h3>${esc(p.name)}</h3><div class="price">${p.oldPrice?`<del>${fmt(p.oldPrice)}</del>`:''}<strong>${fmt(p.price)}</strong></div><div class="pix"><span>PIX</span> ${fmt(pix(p.price))}</div><span class="cta">Ver produto <b>→</b></span></div></a></article>`;}
function render(){const q=state.q;let arr=(window.PRODUCTS||[]).filter(p=>isCat(p,state.cat)&&(`${p.name} ${p.category} ${p.version}`).toLowerCase().includes(q));if(state.sort==='menor')arr.sort((a,b)=>a.price-b.price);if(state.sort==='maior')arr.sort((a,b)=>b.price-a.price);const grid=$('#grid');if(!grid)return;if(arr.length)grid.innerHTML=arr.map(card).join('');else grid.innerHTML='<div class="empty"><strong>Nenhum produto encontrado.</strong><span>Tente outro time, coleção ou categoria.</span></div>';const count=$('#count');if(count)count.textContent=`${arr.length} ${arr.length===1?'produto':'produtos'}`;}
function setCat(cat){state.cat=cat;document.querySelectorAll('.category-card').forEach(b=>b.classList.toggle('active',b.dataset.cat===cat));render();const c=$('#catalogo');if(c)c.scrollIntoView({behavior:'smooth',block:'start'});}
function init(){document.querySelectorAll('.category-card').forEach(b=>b.addEventListener('click',()=>setCat(b.dataset.cat)));document.querySelectorAll('[data-nav-cat]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();setCat(a.dataset.navCat)}));const sync=e=>{state.q=e.target.value.toLowerCase().trim();document.querySelectorAll('#search,#searchMobile').forEach(x=>{if(x!==e.target)x.value=e.target.value});render()};$('#search')?.addEventListener('input',sync);$('#searchMobile')?.addEventListener('input',sync);$('#sort')?.addEventListener('change',e=>{state.sort=e.target.value;render()});render();}
document.addEventListener('DOMContentLoaded',init);

// V6: navegação dos produtos é feita por páginas independentes, sem modal.
document.addEventListener('click', function(e){ const a=e.target.closest('a.card-open'); if(a){ window.location.href=a.href; } });
